DELETE http://localhost:8080/events/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAbWFpbC5jb20iLCJleHAiOjE3MjAzODY1NzEsInVzZXJJZCI6MX0.KcRYe492eptbcONV73u8fPvt3sILbtwaGtXUqtJ045o